/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package movieimporter;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import org.jsoup.Jsoup;
import org.jsoup.nodes.Document;
import org.jsoup.nodes.Element;
import org.jsoup.parser.Parser;

/**
 *
 * @author Tushar
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(758, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(102, 102, 102))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(133, 133, 133)
                .addComponent(jButton1)
                .addContainerGap(472, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String s = "This XML file does not appear to have any style information associated with it. The document tree is shown below.\n" +
                "<ListBucketResult xmlns=\"http://s3.amazonaws.com/doc/2006-03-01/\">\n" +
                "<Name>triumphit</Name>\n" +
                "<Prefix/>\n" +
                "<Marker/>\n" +
                "<MaxKeys>1000</MaxKeys>\n" +
                "<IsTruncated>false</IsTruncated>\n" +
                "<Contents>\n" +
                "<Key>Animal Instincts - HD 720p.mp4</Key>\n" +
                "<LastModified>2016-09-28T16:06:19.000Z</LastModified>\n" +
                "<ETag>\"254fb1310176db848165d7587653bd5b-12\"</ETag>\n" +
                "<Size>796894896</Size>\n" +
                "<StorageClass>STANDARD</StorageClass>\n" +
                "</Contents>\n" +
                "<Contents>\n" +
                "<Key>\n" +
                "Eight Days a Week - The Touring Years - HD 720p.mp4\n" +
                "</Key>\n" +
                "<LastModified>2016-09-25T17:30:54.000Z</LastModified>\n" +
                "<ETag>\"a76b62c26f751f30246048f383888705-23\"</ETag>\n" +
                "<Size>1537424649</Size>\n" +
                "<StorageClass>STANDARD</StorageClass>\n" +
                "</Contents>\n" +
                "<Contents>\n" +
                "<Key>Final Fantasy XV - HD 720p.mp4</Key>\n" +
                "<LastModified>2016-09-25T08:41:12.000Z</LastModified>\n" +
                "<ETag>\"004a8020b5baadcd42266e4fd12e2646-19\"</ETag>\n" +
                "<Size>1255472298</Size>\n" +
                "<StorageClass>STANDARD</StorageClass>\n" +
                "</Contents>\n" +
                "<Contents>\n" +
                "<Key>Lost Without You - HDRip.mp4</Key>\n" +
                "<LastModified>2016-09-27T18:28:28.000Z</LastModified>\n" +
                "<ETag>\"47e065aab35b740ed5c6667fd04c819d-5\"</ETag>\n" +
                "<Size>279570588</Size>\n" +
                "<StorageClass>STANDARD</StorageClass>\n" +
                "</Contents>\n" +
                "<Contents>\n" +
                "<Key>Men of Courage - HDRip.mp4</Key>\n" +
                "<LastModified>2016-09-25T07:08:06.000Z</LastModified>\n" +
                "<ETag>\"bc76e21bce70cf61f1b57f7f24a8e754-7\"</ETag>\n" +
                "<Size>412329936</Size>\n" +
                "<StorageClass>STANDARD</StorageClass>\n" +
                "</Contents>\n" +
                "<Contents>\n" +
                "<Key>One Night in Doom House - SD.mp4</Key>\n" +
                "<LastModified>2016-09-28T16:06:31.000Z</LastModified>\n" +
                "<ETag>\"c1d7b82ea95000034f0013a903777aaf-4\"</ETag>\n" +
                "<Size>258231799</Size>\n" +
                "<StorageClass>STANDARD</StorageClass>\n" +
                "</Contents>\n" +
                "<Contents>\n" +
                "<Key>\n" +
                "Mechanic.Resurrection.2016.720p.HDRip.750MB.Ganool.ph.mkv\n" +
                "</Key>\n" +
                "<LastModified>2016-09-28T18:24:53.000Z</LastModified>\n" +
                "<ETag>\"72629dec92b6dde412a9e374311b4121-12\"</ETag>\n" +
                "<Size>787045424</Size>\n" +
                "<StorageClass>STANDARD</StorageClass>\n" +
                "</Contents>\n" +
                "<Contents>\n" +
                "<Key>[fmovies.to] .mp4</Key>\n" +
                "<LastModified>2016-09-26T05:36:29.000Z</LastModified>\n" +
                "<ETag>\"2aefa639acb57a39d09d25f2be73965d-4\"</ETag>\n" +
                "<Size>261529314</Size>\n" +
                "<StorageClass>STANDARD</StorageClass>\n" +
                "</Contents>\n" +
                "<Contents>\n" +
                "<Key>[fmovies.to] 1944 - HDRip.mp4</Key>\n" +
                "<LastModified>2016-09-28T15:24:53.000Z</LastModified>\n" +
                "<ETag>\"33a8cc21a8b7e1569c0690f483983218-6\"</ETag>\n" +
                "<Size>346993238</Size>\n" +
                "<StorageClass>STANDARD</StorageClass>\n" +
                "</Contents>\n" +
                "<Contents>\n" +
                "<Key>[fmovies.to] 31 - HD 720p.mp4</Key>\n" +
                "<LastModified>2016-09-25T06:23:12.000Z</LastModified>\n" +
                "<ETag>\"31e0d5480f9f72d329ea30b5efac047c-18\"</ETag>\n" +
                "<Size>1157353202</Size>\n" +
                "<StorageClass>STANDARD</StorageClass>\n" +
                "</Contents>\n" +
                "<Contents>\n" +
                "<Key>\n" +
                "[fmovies.to] A Dogwalkers Christmas Tale - HDRip.mp4\n" +
                "</Key>\n" +
                "<LastModified>2016-09-28T16:06:49.000Z</LastModified>\n" +
                "<ETag>\"c26cf242d4a07b92452b7d772a79b70c-4\"</ETag>\n" +
                "<Size>233126099</Size>\n" +
                "<StorageClass>STANDARD</StorageClass>\n" +
                "</Contents>\n" +
                "<Contents>\n" +
                "<Key>\n" +
                "[fmovies.to] A Haunting at the Hoyt Library - SD.mp4\n" +
                "</Key>\n" +
                "<LastModified>2016-09-28T16:06:51.000Z</LastModified>\n" +
                "<ETag>\"287d563daad9706621a7aa721758419a-4\"</ETag>\n" +
                "<Size>215925451</Size>\n" +
                "<StorageClass>STANDARD</StorageClass>\n" +
                "</Contents>\n" +
                "<Contents>\n" +
                "<Key>[fmovies.to] A Month of Sundays - HDRip.mp4</Key>\n" +
                "<LastModified>2016-09-28T15:25:07.000Z</LastModified>\n" +
                "<ETag>\"34215e609e3303294354d3c3c7a47e11-6\"</ETag>\n" +
                "<Size>344318692</Size>\n" +
                "<StorageClass>STANDARD</StorageClass>\n" +
                "</Contents>\n" +
                "<Contents>\n" +
                "<Key>[fmovies.to] ARQ - HD 720p.mp4</Key>\n" +
                "<LastModified>2016-09-24T11:46:47.000Z</LastModified>\n" +
                "<ETag>\"5dab5b3524a07d6455f2446b55d3f6e8-14\"</ETag>\n" +
                "<Size>909794544</Size>\n" +
                "<StorageClass>STANDARD</StorageClass>\n" +
                "</Contents>\n" +
                "<Contents>\n" +
                "<Key>[fmovies.to] Abattoir - HD 1080p.mp4</Key>\n" +
                "<LastModified>2016-09-28T15:25:17.000Z</LastModified>\n" +
                "<ETag>\"d3fd21342ae33a77ed745e7c3e7f90a8-13\"</ETag>\n" +
                "<Size>822636145</Size>\n" +
                "<StorageClass>STANDARD</StorageClass>\n" +
                "</Contents>\n" +
                "<Contents>\n" +
                "<Key>[fmovies.to] All Out Dysfunktion! - HD 720p.mp4</Key>\n" +
                "<LastModified>2016-09-26T05:36:45.000Z</LastModified>\n" +
                "<ETag>\"86f25c3fed13ec2d0469bcd19832a6ff-12\"</ETag>\n" +
                "<Size>748935032</Size>\n" +
                "<StorageClass>STANDARD</StorageClass>\n" +
                "</Contents>\n" +
                "<Contents>\n" +
                "<Key>[fmovies.to] AmeriGeddon - HD 1080p.mp4</Key>\n" +
                "<LastModified>2016-09-26T05:37:01.000Z</LastModified>\n" +
                "<ETag>\"502c25985d5318c41e871b570887eea8-14\"</ETag>\n" +
                "<Size>925683626</Size>\n" +
                "<StorageClass>STANDARD</StorageClass>\n" +
                "</Contents>\n" +
                "<Contents>\n" +
                "<Key>[fmovies.to] An Inspector Calls - HD 1080p.mp4</Key>\n" +
                "<LastModified>2016-09-28T16:07:03.000Z</LastModified>\n" +
                "<ETag>\"5604ca7c763b480fe998390cdee21532-22\"</ETag>\n" +
                "<Size>1467963999</Size>\n" +
                "<StorageClass>STANDARD</StorageClass>\n" +
                "</Contents>\n" +
                "<Contents>\n" +
                "<Key>[fmovies.to] Angel of Reckoning - HD 720p.mp4</Key>\n" +
                "<LastModified>2016-09-26T05:14:27.000Z</LastModified>\n" +
                "<ETag>\"50b584b1eacb36e6d5318546fd4f3f7e-23\"</ETag>\n" +
                "<Size>1541012734</Size>\n" +
                "<StorageClass>STANDARD</StorageClass>\n" +
                "</Contents>\n" +
                "<Contents>\n" +
                "<Key>[fmovies.to] Antibirth - HD 720p.mp4</Key>\n" +
                "<LastModified>2016-09-25T08:23:00.000Z</LastModified>\n" +
                "<ETag>\"6eaa6fa9e6d9a63034e37313d041eb35-16\"</ETag>\n" +
                "<Size>1072095599</Size>\n" +
                "<StorageClass>STANDARD</StorageClass>\n" +
                "</Contents>\n" +
                "<Contents>\n" +
                "<Key>[fmovies.to] Backstabbed - HDRip.mp4</Key>\n" +
                "<LastModified>2016-09-28T16:07:15.000Z</LastModified>\n" +
                "<ETag>\"6f0db3b508b608b4b31a68205f92e730-4\"</ETag>\n" +
                "<Size>268190488</Size>\n" +
                "<StorageClass>STANDARD</StorageClass>\n" +
                "</Contents>\n" +
                "<Contents>\n" +
                "<Key>[fmovies.to] Blair Witch - CAM.mp4</Key>\n" +
                "<LastModified>2016-09-25T06:15:46.000Z</LastModified>\n" +
                "<ETag>\"772d93d7fde0698cb7660e73e27c2d08-5\"</ETag>\n" +
                "<Size>333764739</Size>\n" +
                "<StorageClass>STANDARD</StorageClass>\n" +
                "</Contents>\n" +
                "<Contents>\n" +
                "<Key>[fmovies.to] Blood Trap - HDRip.mp4</Key>\n" +
                "<LastModified>2016-09-26T04:53:22.000Z</LastModified>\n" +
                "<ETag>\"c465f2106aa9e50559c7a6e5e37ba3d5-4\"</ETag>\n" +
                "<Size>255350703</Size>\n" +
                "<StorageClass>STANDARD</StorageClass>\n" +
                "</Contents>\n" +
                "<Contents>\n" +
                "<Key>[fmovies.to] Bolshoi Babylon - SD.dat</Key>\n" +
                "<LastModified>2016-09-26T06:12:03.000Z</LastModified>\n" +
                "<ETag>\"98170eaba107a7e423da16efaad68538-4\"</ETag>\n" +
                "<Size>267338154</Size>\n" +
                "<StorageClass>STANDARD</StorageClass>\n" +
                "</Contents>\n" +
                "<Contents>\n" +
                "<Key>[fmovies.to] Bridget Joness Baby - CAM.mp4</Key>\n" +
                "<LastModified>2016-09-26T05:14:41.000Z</LastModified>\n" +
                "<ETag>\"61e5ca116d148248c55e85ad31d9e272-6\"</ETag>\n" +
                "<Size>342704944</Size>\n" +
                "<StorageClass>STANDARD</StorageClass>\n" +
                "</Contents>\n" +
                "<Contents>\n" +
                "<Key>[fmovies.to] Brother Nature - HD 720p.mp4</Key>\n" +
                "<LastModified>2016-09-28T16:07:39.000Z</LastModified>\n" +
                "<ETag>\"f004e4c5932e530ada7599dce3e6cf2d-6\"</ETag>\n" +
                "<Size>375570472</Size>\n" +
                "<StorageClass>STANDARD</StorageClass>\n" +
                "</Contents>\n" +
                "<Contents>\n" +
                "<Key>[fmovies.to] Caged No More - SD.mp4</Key>\n" +
                "<LastModified>2016-09-28T15:25:29.000Z</LastModified>\n" +
                "<ETag>\"cdd035d93c95e645ff242307a8d97f78-5\"</ETag>\n" +
                "<Size>272365586</Size>\n" +
                "<StorageClass>STANDARD</StorageClass>\n" +
                "</Contents>\n" +
                "<Contents>\n" +
                "<Key>[fmovies.to] Capsule - HDRip.mp4</Key>\n" +
                "<LastModified>2016-09-25T17:47:09.000Z</LastModified>\n" +
                "<ETag>\"430e31bcc01d8f9b65e135398d78ef0c-4\"</ETag>\n" +
                "<Size>241950785</Size>\n" +
                "<StorageClass>STANDARD</StorageClass>\n" +
                "</Contents>\n" +
                "<Contents>\n" +
                "<Key>[fmovies.to] ChickLit - HDRip.mp4</Key>\n" +
                "<LastModified>2016-09-25T18:02:46.000Z</LastModified>\n" +
                "<ETag>\"f52c7e0da29b625453549c2ccd2ab18f-5\"</ETag>\n" +
                "<Size>317195461</Size>\n" +
                "<StorageClass>STANDARD</StorageClass>\n" +
                "</Contents>\n" +
                "<Contents>\n" +
                "<Key>[fmovies.to] Complete Unknown - SD.mp4</Key>\n" +
                "<LastModified>2016-09-27T18:28:45.000Z</LastModified>\n" +
                "<ETag>\"f1d2b8e91ce1037345768545eb2a15d5-4\"</ETag>\n" +
                "<Size>231851233</Size>\n" +
                "<StorageClass>STANDARD</StorageClass>\n" +
                "</Contents>\n" +
                "<Contents>\n" +
                "<Key>[fmovies.to] Dark Exorcism - HDRip.dat</Key>\n" +
                "<LastModified>2016-09-26T06:25:28.000Z</LastModified>\n" +
                "<ETag>\"ee1356cb92266fd13cb26f89ae1d70eb-4\"</ETag>\n" +
                "<Size>231698507</Size>\n" +
                "<StorageClass>STANDARD</StorageClass>\n" +
                "</Contents>\n" +
                "<Contents>\n" +
                "<Key>[fmovies.to] Deserted - SD.dat</Key>\n" +
                "<LastModified>2016-09-26T06:12:16.000Z</LastModified>\n" +
                "<ETag>\"f1bcd810ec2bc498c4463650fbb8c77c-5\"</ETag>\n" +
                "<Size>271300747</Size>\n" +
                "<StorageClass>STANDARD</StorageClass>\n" +
                "</Contents>\n" +
                "<Contents>\n" +
                "<Key>[fmovies.to] Dirty 30 - HD 720p.mp4</Key>\n" +
                "<LastModified>2016-09-25T17:49:26.000Z</LastModified>\n" +
                "<ETag>\"713a10413a792d94a15ccec362754d17-17\"</ETag>\n" +
                "<Size>1128354361</Size>\n" +
                "<StorageClass>STANDARD</StorageClass>\n" +
                "</Contents>\n" +
                "<Contents>\n" +
                "<Key>[fmovies.to] Dont Breathe - CAM.mp4</Key>\n" +
                "<LastModified>2016-09-25T07:27:04.000Z</LastModified>\n" +
                "<ETag>\"10d4cc4dd0092a8820c2730b09a2e2e1-4\"</ETag>\n" +
                "<Size>213008270</Size>\n" +
                "<StorageClass>STANDARD</StorageClass>\n" +
                "</Contents>\n" +
                "<Contents>\n" +
                "<Key>[fmovies.to] Downriver - SD.dat</Key>\n" +
                "<LastModified>2016-09-26T06:12:30.000Z</LastModified>\n" +
                "<ETag>\"65d62bf4b80f4f00adab0bb94e83af48-5\"</ETag>\n" +
                "<Size>289640968</Size>\n" +
                "<StorageClass>STANDARD</StorageClass>\n" +
                "</Contents>\n" +
                "<Contents>\n" +
                "<Key>[fmovies.to] Eden - HD 1080p.mp4</Key>\n" +
                "<LastModified>2016-09-26T05:15:31.000Z</LastModified>\n" +
                "<ETag>\"2a0d85076a800031aa697061b66679d6-14\"</ETag>\n" +
                "<Size>910549150</Size>\n" +
                "<StorageClass>STANDARD</StorageClass>\n" +
                "</Contents>\n" +
                "<Contents>\n" +
                "<Key>[fmovies.to] End of a Gun - HDRip.mp4</Key>\n" +
                "<LastModified>2016-09-25T17:47:33.000Z</LastModified>\n" +
                "<ETag>\"db8a9a23971e8c378b02a01e2df9ff8e-5\"</ETag>\n" +
                "<Size>275604772</Size>\n" +
                "<StorageClass>STANDARD</StorageClass>\n" +
                "</Contents>\n" +
                "<Contents>\n" +
                "<Key>[fmovies.to] Finders Keepers - HD 720p.mp4</Key>\n" +
                "<LastModified>2016-09-28T16:07:55.000Z</LastModified>\n" +
                "<ETag>\"8e0bcdf3d8aa5867c13bf4d7758e0580-14\"</ETag>\n" +
                "<Size>925490732</Size>\n" +
                "<StorageClass>STANDARD</StorageClass>\n" +
                "</Contents>\n" +
                "<Contents>\n" +
                "<Key>[fmovies.to] Flight Crew - HD 1080p.mp4</Key>\n" +
                "<LastModified>2016-09-28T15:25:55.000Z</LastModified>\n" +
                "<ETag>\"7dde4ea231799ff99e72728f93ed64cb-23\"</ETag>\n" +
                "<Size>1489927140</Size>\n" +
                "<StorageClass>STANDARD</StorageClass>\n" +
                "</Contents>\n" +
                "<Contents>\n" +
                "<Key>[fmovies.to] Flirting with Madness - HD 720p.mp4</Key>\n" +
                "<LastModified>2016-09-25T17:30:12.000Z</LastModified>\n" +
                "<ETag>\"f1de7c6f950eccd80960cf06722198ff-15\"</ETag>\n" +
                "<Size>943300080</Size>\n" +
                "<StorageClass>STANDARD</StorageClass>\n" +
                "</Contents>\n" +
                "<Contents>\n" +
                "<Key>[fmovies.to] Food Choices - HD 720p.mp4</Key>\n" +
                "<LastModified>2016-09-27T18:29:01.000Z</LastModified>\n" +
                "<ETag>\"65d60ecaaf9c69a5aaa6e2e9e7e936cf-17\"</ETag>\n" +
                "<Size>1108534551</Size>\n" +
                "<StorageClass>STANDARD</StorageClass>\n" +
                "</Contents>\n" +
                "<Contents>\n" +
                "<Key>[fmovies.to] For the Love of Spock - HDRip.mp4</Key>\n" +
                "<LastModified>2016-09-28T15:26:27.000Z</LastModified>\n" +
                "<ETag>\"3b6e6b508dc47d20a0875bf95fd68ae0-6\"</ETag>\n" +
                "<Size>345628860</Size>\n" +
                "<StorageClass>STANDARD</StorageClass>\n" +
                "</Contents>\n" +
                "<Contents>\n" +
                "<Key>[fmovies.to] Free State of Jones - HD 720p.mp4</Key>\n" +
                "<LastModified>2016-09-25T08:23:14.000Z</LastModified>\n" +
                "<ETag>\"2760455658a57b25721c4d16de48d76f-25\"</ETag>\n" +
                "<Size>1644597287</Size>\n" +
                "<StorageClass>STANDARD</StorageClass>\n" +
                "</Contents>\n" +
                "<Contents>\n" +
                "<Key>[fmovies.to] Friend Request - HD 720p.mp4</Key>\n" +
                "<LastModified>2016-09-25T07:26:22.000Z</LastModified>\n" +
                "<ETag>\"6d79381a128f6d254c8c0bcf80264e27-13\"</ETag>\n" +
                "<Size>838051568</Size>\n" +
                "<StorageClass>STANDARD</StorageClass>\n" +
                "</Contents>\n" +
                "<Contents>\n" +
                "<Key>\n" +
                "[fmovies.to] Gangsters Gamblers Geezers - HDRip.mp4\n" +
                "</Key>\n" +
                "<LastModified>2016-09-26T04:53:36.000Z</LastModified>\n" +
                "<ETag>\"2c6b9ac06b602b8807988541dd746f36-6\"</ETag>\n" +
                "<Size>367031965</Size>\n" +
                "<StorageClass>STANDARD</StorageClass>\n" +
                "</Contents>\n" +
                "<Contents>\n" +
                "<Key>[fmovies.to] Ghost Squad - HDRip.dat</Key>\n" +
                "<LastModified>2016-09-26T06:25:41.000Z</LastModified>\n" +
                "<ETag>\"8853ab9636208804afb5f48a5e9bc69c-4\"</ETag>\n" +
                "<Size>262005970</Size>\n" +
                "<StorageClass>STANDARD</StorageClass>\n" +
                "</Contents>\n" +
                "<Contents>\n" +
                "<Key>[fmovies.to] Ghostbusters - HD 720p.mp4</Key>\n" +
                "<LastModified>2016-09-24T20:53:16.000Z</LastModified>\n" +
                "<ETag>\"ac5b0bd9ca4cfbbce10b8c9abf272cd7-24\"</ETag>\n" +
                "<Size>1574861159</Size>\n" +
                "<StorageClass>STANDARD</StorageClass>\n" +
                "</Contents>\n" +
                "<Contents>\n" +
                "<Key>[fmovies.to] Goat - HDRip.mp4</Key>\n" +
                "<LastModified>2016-09-25T17:47:51.000Z</LastModified>\n" +
                "<ETag>\"086f954d67ad05d36d12769ea088078c-6\"</ETag>\n" +
                "<Size>363530490</Size>\n" +
                "<StorageClass>STANDARD</StorageClass>\n" +
                "</Contents>\n" +
                "<Contents>\n" +
                "<Key>[fmovies.to] Gods Compass - HDRip.mp4</Key>\n" +
                "<LastModified>2016-09-28T15:26:43.000Z</LastModified>\n" +
                "<ETag>\"9487d6f8fc2ab8ce33bdf8f0d97788bc-4\"</ETag>\n" +
                "<Size>253684579</Size>\n" +
                "<StorageClass>STANDARD</StorageClass>\n" +
                "</Contents>\n" +
                "<Contents>\n" +
                "<Key>[fmovies.to] Happy Birthday - HD 720p.mp4</Key>\n" +
                "<LastModified>2016-09-28T15:27:00.000Z</LastModified>\n" +
                "<ETag>\"f4416ed3484dd0d2240350efbde37b27-12\"</ETag>\n" +
                "<Size>794542718</Size>\n" +
                "<StorageClass>STANDARD</StorageClass>\n" +
                "</Contents>\n" +
                "<Contents>\n" +
                "<Key>[fmovies.to] Honeymoon From Hell - HDRip.mp4</Key>\n" +
                "<LastModified>2016-09-28T16:08:41.000Z</LastModified>\n" +
                "<ETag>\"96e15f597f29ba070707b699850c7ec9-4\"</ETag>\n" +
                "<Size>256485086</Size>\n" +
                "<StorageClass>STANDARD</StorageClass>\n" +
                "</Contents>\n" +
                "<Contents>\n" +
                "<Key>[fmovies.to] Huntwatch - HD 720p.mp4</Key>\n" +
                "<LastModified>2016-09-25T17:29:20.000Z</LastModified>\n" +
                "<ETag>\"24550d09cad37073c422bbb7973e29ff-15\"</ETag>\n" +
                "<Size>979724488</Size>\n" +
                "<StorageClass>STANDARD</StorageClass>\n" +
                "</Contents>\n" +
                "<Contents>\n" +
                "<Key>[fmovies.to] I Am Hooligan - HDRip.mp4</Key>\n" +
                "<LastModified>2016-09-28T16:08:53.000Z</LastModified>\n" +
                "<ETag>\"45304b450fb581f31644c56c559ab613-5\"</ETag>\n" +
                "<Size>316655607</Size>\n" +
                "<StorageClass>STANDARD</StorageClass>\n" +
                "</Contents>\n" +
                "<Contents>\n" +
                "<Key>[fmovies.to] I.T. - HD 720p.mp4</Key>\n" +
                "<LastModified>2016-09-25T18:03:02.000Z</LastModified>\n" +
                "<ETag>\"98a78a96c6212127e5ad1c2c4804f9e2-13\"</ETag>\n" +
                "<Size>810845627</Size>\n" +
                "<StorageClass>STANDARD</StorageClass>\n" +
                "</Contents>\n" +
                "<Contents>\n" +
                "<Key>[fmovies.to] ISRA 88 - HD 720p.dat</Key>\n" +
                "<LastModified>2016-09-26T06:25:57.000Z</LastModified>\n" +
                "<ETag>\"1ba12815d52115e192f494b50f07fafe-14\"</ETag>\n" +
                "<Size>926055619</Size>\n" +
                "<StorageClass>STANDARD</StorageClass>\n" +
                "</Contents>\n" +
                "<Contents>\n" +
                "<Key>[fmovies.to] Interrogation - HD 1080p.mp4</Key>\n" +
                "<LastModified>2016-09-28T16:09:07.000Z</LastModified>\n" +
                "<ETag>\"5a952474919bc12e7d3b1aafc7f37a70-17\"</ETag>\n" +
                "<Size>1105589962</Size>\n" +
                "<StorageClass>STANDARD</StorageClass>\n" +
                "</Contents>\n" +
                "<Contents>\n" +
                "<Key>[fmovies.to] Ithaca - HD 720p.mp4</Key>\n" +
                "<LastModified>2016-09-28T15:27:06.000Z</LastModified>\n" +
                "<ETag>\"486ee26669f256672a1077d8f745af8f-11\"</ETag>\n" +
                "<Size>714963805</Size>\n" +
                "<StorageClass>STANDARD</StorageClass>\n" +
                "</Contents>\n" +
                "<Contents>\n" +
                "<Key>[fmovies.to] Kids in Love - HDRip.mp4</Key>\n" +
                "<LastModified>2016-09-25T08:37:43.000Z</LastModified>\n" +
                "<ETag>\"7bcba646f04881e1c20801f33fd62848-4\"</ETag>\n" +
                "<Size>244393021</Size>\n" +
                "<StorageClass>STANDARD</StorageClass>\n" +
                "</Contents>\n" +
                "<Contents>\n" +
                "<Key>[fmovies.to] KillerSaurus - SD.mp4</Key>\n" +
                "<LastModified>2016-09-25T17:28:58.000Z</LastModified>\n" +
                "<ETag>\"b1cce45502d4a81f69e69258cbdba1b6-4\"</ETag>\n" +
                "<Size>209838977</Size>\n" +
                "<StorageClass>STANDARD</StorageClass>\n" +
                "</Contents>\n" +
                "<Contents>\n" +
                "<Key>[fmovies.to] Killing Mommy - HDRip.mp4</Key>\n" +
                "<LastModified>2016-09-28T16:10:12.000Z</LastModified>\n" +
                "<ETag>\"00d88cf84576e231bd2f50b3750106c2-4\"</ETag>\n" +
                "<Size>260201254</Size>\n" +
                "<StorageClass>STANDARD</StorageClass>\n" +
                "</Contents>\n" +
                "<Contents>\n" +
                "<Key>[fmovies.to] Kubo and the Two Strings - TS.mp4</Key>\n" +
                "<LastModified>2016-09-25T07:08:22.000Z</LastModified>\n" +
                "<ETag>\"3c0898b82232dcb4e55fb17ac4e481ea-4\"</ETag>\n" +
                "<Size>259850019</Size>\n" +
                "<StorageClass>STANDARD</StorageClass>\n" +
                "</Contents>\n" +
                "<Contents>\n" +
                "<Key>[fmovies.to] League of Gods - HD 720p.mp4</Key>\n" +
                "<LastModified>2016-09-26T04:53:50.000Z</LastModified>\n" +
                "<ETag>\"4a14434fb9726aa317502a75ba2f368f-24\"</ETag>\n" +
                "<Size>1560644263</Size>\n" +
                "<StorageClass>STANDARD</StorageClass>\n" +
                "</Contents>\n" +
                "<Contents>\n" +
                "<Key>[fmovies.to] Lethal Seduction - HDRip.mp4</Key>\n" +
                "<LastModified>2016-09-28T16:11:16.000Z</LastModified>\n" +
                "<ETag>\"4d691071c23024a16abcfcc6300b5b71-4\"</ETag>\n" +
                "<Size>254764809</Size>\n" +
                "<StorageClass>STANDARD</StorageClass>\n" +
                "</Contents>\n" +
                "<Contents>\n" +
                "<Key>[fmovies.to] Level Up - HD 720p.mp4</Key>\n" +
                "<LastModified>2016-09-28T16:11:28.000Z</LastModified>\n" +
                "<ETag>\"f34bc2927423a426f0673ac5bce8d978-12\"</ETag>\n" +
                "<Size>764800737</Size>\n" +
                "<StorageClass>STANDARD</StorageClass>\n" +
                "</Contents>\n" +
                "<Contents>\n" +
                "<Key>[fmovies.to] Ma ma - HDRip.dat</Key>\n" +
                "<LastModified>2016-09-26T06:26:21.000Z</LastModified>\n" +
                "<ETag>\"446143cb925a0cd54f11bc8e595e620f-5\"</ETag>\n" +
                "<Size>310237240</Size>\n" +
                "<StorageClass>STANDARD</StorageClass>\n" +
                "</Contents>\n" +
                "<Contents>\n" +
                "<Key>[fmovies.to] Major Deal - HDRip.mp4</Key>\n" +
                "<LastModified>2016-09-27T18:29:51.000Z</LastModified>\n" +
                "<ETag>\"a6c4faca6feecc95c14f3477134757c5-12\"</ETag>\n" +
                "<Size>776793775</Size>\n" +
                "<StorageClass>STANDARD</StorageClass>\n" +
                "</Contents>\n" +
                "<Contents>\n" +
                "<Key>[fmovies.to] Major Deal - HDRip[0].mp4</Key>\n" +
                "<LastModified>2016-09-27T18:30:05.000Z</LastModified>\n" +
                "<ETag>\"a6c4faca6feecc95c14f3477134757c5-12\"</ETag>\n" +
                "<Size>776793775</Size>\n" +
                "<StorageClass>STANDARD</StorageClass>\n" +
                "</Contents>\n" +
                "<Contents>\n" +
                "<Key>[fmovies.to] Max e Hélène - SD.mp4</Key>\n" +
                "<LastModified>2016-09-28T15:28:02.000Z</LastModified>\n" +
                "<ETag>\"9b729efc7a8947e8e1970d89a1ec245a-7\"</ETag>\n" +
                "<Size>433404379</Size>\n" +
                "<StorageClass>STANDARD</StorageClass>\n" +
                "</Contents>\n" +
                "<Contents>\n" +
                "<Key>[fmovies.to] Men .mp4</Key>\n" +
                "<LastModified>2016-09-26T05:15:51.000Z</LastModified>\n" +
                "<ETag>\"1cd4279c0aac6cb24daac26698d48bb8-14\"</ETag>\n" +
                "<Size>885849706</Size>\n" +
                "<StorageClass>STANDARD</StorageClass>\n" +
                "</Contents>\n" +
                "<Contents>\n" +
                "<Key>[fmovies.to] Miss Stevens - HDRip.mp4</Key>\n" +
                "<LastModified>2016-09-26T05:17:12.000Z</LastModified>\n" +
                "<ETag>\"a77a88767fb96db5ef377514a0b29463-4\"</ETag>\n" +
                "<Size>238314012</Size>\n" +
                "<StorageClass>STANDARD</StorageClass>\n" +
                "</Contents>\n" +
                "<Contents>\n" +
                "<Key>[fmovies.to] Morgan - CAM.mp4</Key>\n" +
                "<LastModified>2016-09-25T07:26:02.000Z</LastModified>\n" +
                "<ETag>\"00493cc80f6c12e1a4a425273b2a5e16-4\"</ETag>\n" +
                "<Size>227020677</Size>\n" +
                "<StorageClass>STANDARD</StorageClass>\n" +
                "</Contents>\n" +
                "<Contents>\n" +
                "<Key>[fmovies.to] My Favorite Five - HD 720p.mp4</Key>\n" +
                "<LastModified>2016-09-28T16:11:58.000Z</LastModified>\n" +
                "<ETag>\"66b1ad8af2689676e441c014db572774-15\"</ETag>\n" +
                "<Size>1000129610</Size>\n" +
                "<StorageClass>STANDARD</StorageClass>\n" +
                "</Contents>\n" +
                "<Contents>\n" +
                "<Key>[fmovies.to] One Piece Film Gold - CAM.mp4</Key>\n" +
                "<LastModified>2016-09-25T08:23:40.000Z</LastModified>\n" +
                "<ETag>\"a67740a99ffec0d84dfcafcbc10194d1-8\"</ETag>\n" +
                "<Size>512370723</Size>\n" +
                "<StorageClass>STANDARD</StorageClass>\n" +
                "</Contents>\n" +
                "<Contents>\n" +
                "<Key>[fmovies.to] Parched - HD 720p.dat</Key>\n" +
                "<LastModified>2016-09-26T06:26:34.000Z</LastModified>\n" +
                "<ETag>\"8aba5be91a814b4fc49a052a42986750-19\"</ETag>\n" +
                "<Size>1269025391</Size>\n" +
                "<StorageClass>STANDARD</StorageClass>\n" +
                "</Contents>\n" +
                "<Contents>\n" +
                "<Key>[fmovies.to] Petes Dragon - TS.mp4</Key>\n" +
                "<LastModified>2016-09-25T08:24:02.000Z</LastModified>\n" +
                "<ETag>\"b247ca0801340185f74a52b5faf0eb88-4\"</ETag>\n" +
                "<Size>263711486</Size>\n" +
                "<StorageClass>STANDARD</StorageClass>\n" +
                "</Contents>\n" +
                "<Contents>\n" +
                "<Key>[fmovies.to] Point Break - HD 1080p.mp4</Key>\n" +
                "<LastModified>2016-09-24T20:03:13.000Z</LastModified>\n" +
                "<ETag>\"b596205dd94a8dee3ad3be401b8000ce-25\"</ETag>\n" +
                "<Size>1635956795</Size>\n" +
                "<StorageClass>STANDARD</StorageClass>\n" +
                "</Contents>\n" +
                "<Contents>\n" +
                "<Key>[fmovies.to] Rattle the Cage - SD.mp4</Key>\n" +
                "<LastModified>2016-09-26T05:17:26.000Z</LastModified>\n" +
                "<ETag>\"6601e80c3ece22367fe14c10c0ad0f3f-4\"</ETag>\n" +
                "<Size>247800810</Size>\n" +
                "<StorageClass>STANDARD</StorageClass>\n" +
                "</Contents>\n" +
                "<Contents>\n" +
                "<Key>[fmovies.to] Redistributors - HD 720p.dat</Key>\n" +
                "<LastModified>2016-09-26T05:37:57.000Z</LastModified>\n" +
                "<ETag>\"f0a5dd95cb2ab67fa9815e03dcb0cb2c-12\"</ETag>\n" +
                "<Size>799999862</Size>\n" +
                "<StorageClass>STANDARD</StorageClass>\n" +
                "</Contents>\n" +
                "<Contents>\n" +
                "<Key>[fmovies.to] Ringside - HD 720p.dat</Key>\n" +
                "<LastModified>2016-09-26T06:27:10.000Z</LastModified>\n" +
                "<ETag>\"27a240e602e1ff521ad103dd953436af-20\"</ETag>\n" +
                "<Size>1328330698</Size>\n" +
                "<StorageClass>STANDARD</StorageClass>\n" +
                "</Contents>\n" +
                "<Contents>\n" +
                "<Key>[fmovies.to] San Andreas - HD 1080p.mp4</Key>\n" +
                "<LastModified>2016-09-24T20:29:17.000Z</LastModified>\n" +
                "<ETag>\"f60a0ef6091d2c9aa87a73914cbead08-20\"</ETag>\n" +
                "<Size>1318160900</Size>\n" +
                "<StorageClass>STANDARD</StorageClass>\n" +
                "</Contents>\n" +
                "<Contents>\n" +
                "<Key>[fmovies.to] Silicon Cowboys - HD 720p.mp4</Key>\n" +
                "<LastModified>2016-09-27T18:30:37.000Z</LastModified>\n" +
                "<ETag>\"2cd9de13c31ff412343fa2cab62fb1f5-13\"</ETag>\n" +
                "<Size>864761773</Size>\n" +
                "<StorageClass>STANDARD</StorageClass>\n" +
                "</Contents>\n" +
                "<Contents>\n" +
                "<Key>[fmovies.to] Skiptrace - HD 1080p.mp4</Key>\n" +
                "<LastModified>2016-09-25T08:24:16.000Z</LastModified>\n" +
                "<ETag>\"8babf179b44e5e427144195691d85c72-19\"</ETag>\n" +
                "<Size>1258848483</Size>\n" +
                "<StorageClass>STANDARD</StorageClass>\n" +
                "</Contents>\n" +
                "<Contents>\n" +
                "<Key>[fmovies.to] Snowden (Russian Audio) - CAM.mp4</Key>\n" +
                "<LastModified>2016-09-24T20:54:18.000Z</LastModified>\n" +
                "<ETag>\"a457290a6ed40c08f831f72f1d331fbd-9\"</ETag>\n" +
                "<Size>592930632</Size>\n" +
                "<StorageClass>STANDARD</StorageClass>\n" +
                "</Contents>\n" +
                "<Contents>\n" +
                "<Key>[fmovies.to] Sorority Slaughterhouse - SD.mp4</Key>\n" +
                "<LastModified>2016-09-25T17:28:44.000Z</LastModified>\n" +
                "<ETag>\"349cf3f31a37b8d6280a7f65adc80edb-5\"</ETag>\n" +
                "<Size>311716963</Size>\n" +
                "<StorageClass>STANDARD</StorageClass>\n" +
                "</Contents>\n" +
                "<Contents>\n" +
                "<Key>[fmovies.to] Steel - SD.mp4</Key>\n" +
                "<LastModified>2016-09-28T15:28:02.000Z</LastModified>\n" +
                "<ETag>\"a4cca8b29cd3500d90d2093053454152-5\"</ETag>\n" +
                "<Size>299735939</Size>\n" +
                "<StorageClass>STANDARD</StorageClass>\n" +
                "</Contents>\n" +
                "<Contents>\n" +
                "<Key>[fmovies.to] Suicide Squad - TS.mp4</Key>\n" +
                "<LastModified>2016-09-26T18:47:41.000Z</LastModified>\n" +
                "<ETag>\"3e9ea918ace3a4efe5237795b01d2070-5\"</ETag>\n" +
                "<Size>313081889</Size>\n" +
                "<StorageClass>STANDARD</StorageClass>\n" +
                "</Contents>\n" +
                "<Contents>\n" +
                "<Key>[fmovies.to] Sully - TS.mp4</Key>\n" +
                "<LastModified>2016-09-25T07:08:42.000Z</LastModified>\n" +
                "<ETag>\"d057f02eb98f9b468c21993cff8f3be2-6\"</ETag>\n" +
                "<Size>343230323</Size>\n" +
                "<StorageClass>STANDARD</StorageClass>\n" +
                "</Contents>\n" +
                "<Contents>\n" +
                "<Key>[fmovies.to] Swiss Army Man - HD 1080p.mp4</Key>\n" +
                "<LastModified>2016-09-24T20:55:07.000Z</LastModified>\n" +
                "<ETag>\"ef78c8f87a268ab5c59154a20aa2493e-18\"</ETag>\n" +
                "<Size>1170728187</Size>\n" +
                "<StorageClass>STANDARD</StorageClass>\n" +
                "</Contents>\n" +
                "<Contents>\n" +
                "<Key>[fmovies.to] Tab Hunter Confidential - SD.dat</Key>\n" +
                "<LastModified>2016-09-26T06:12:44.000Z</LastModified>\n" +
                "<ETag>\"39bc07bd8fbaa8b06df5fc0e99ba9d7c-5\"</ETag>\n" +
                "<Size>297764230</Size>\n" +
                "<StorageClass>STANDARD</StorageClass>\n" +
                "</Contents>\n" +
                "<Contents>\n" +
                "<Key>[fmovies.to] Tell Me How I Die - HD 720p.dat</Key>\n" +
                "<LastModified>2016-09-26T06:12:56.000Z</LastModified>\n" +
                "<ETag>\"e5c595ce6555a82dd4ac697e7c9ee595-5\"</ETag>\n" +
                "<Size>305328254</Size>\n" +
                "<StorageClass>STANDARD</StorageClass>\n" +
                "</Contents>\n" +
                "<Contents>\n" +
                "<Key>\n" +
                "[fmovies.to] The 68th Primetime Emmy Awards - HDRip.mp4\n" +
                "</Key>\n" +
                "<LastModified>2016-09-27T18:30:43.000Z</LastModified>\n" +
                "<ETag>\"6511a14188acce5315abe156a8394fc3-9\"</ETag>\n" +
                "<Size>552259119</Size>\n" +
                "<StorageClass>STANDARD</StorageClass>\n" +
                "</Contents>\n" +
                "<Contents>\n" +
                "<Key>[fmovies.to] The Choice - HD 720p.mp4</Key>\n" +
                "<LastModified>2016-09-24T20:27:29.000Z</LastModified>\n" +
                "<ETag>\"6418660cb3e86c4d39c5395650596cc7-16\"</ETag>\n" +
                "<Size>1055280857</Size>\n" +
                "<StorageClass>STANDARD</StorageClass>\n" +
                "</Contents>\n" +
                "<Contents>\n" +
                "<Key>[fmovies.to] The Devils Dolls - HDRip.mp4</Key>\n" +
                "<LastModified>2016-09-25T18:03:54.000Z</LastModified>\n" +
                "<ETag>\"47727e4caa51a411323b1294463fa045-4\"</ETag>\n" +
                "<Size>254838949</Size>\n" +
                "<StorageClass>STANDARD</StorageClass>\n" +
                "</Contents>\n" +
                "<Contents>\n" +
                "<Key>[fmovies.to] The Fits - HD 720p.dat</Key>\n" +
                "<LastModified>2016-09-26T06:28:06.000Z</LastModified>\n" +
                "<ETag>\"49f2c427fa272d042de040e1538a53f9-19\"</ETag>\n" +
                "<Size>1212608832</Size>\n" +
                "<StorageClass>STANDARD</StorageClass>\n" +
                "</Contents>\n" +
                "<Contents>\n" +
                "<Key>[fmovies.to] The Last Bid - HDRip.mp4</Key>\n" +
                "<LastModified>2016-09-27T18:31:05.000Z</LastModified>\n" +
                "<ETag>\"40cb0967ea6f94a5dafb97005de2d754-5\"</ETag>\n" +
                "<Size>284821013</Size>\n" +
                "<StorageClass>STANDARD</StorageClass>\n" +
                "</Contents>\n" +
                "<Contents>\n" +
                "<Key>[fmovies.to] The Light Between Oceans - TS.mp4</Key>\n" +
                "<LastModified>2016-09-25T06:17:51.000Z</LastModified>\n" +
                "<ETag>\"25e3097210a8d609af03fe00f303b68d-6\"</ETag>\n" +
                "<Size>355970777</Size>\n" +
                "<StorageClass>STANDARD</StorageClass>\n" +
                "</Contents>\n" +
                "<Contents>\n" +
                "<Key>[fmovies.to] The Magnificent Seven - CAM.mp4</Key>\n" +
                "<LastModified>2016-09-27T18:31:13.000Z</LastModified>\n" +
                "<ETag>\"c7a8322c99db42ccbf908f899e1f526c-8\"</ETag>\n" +
                "<Size>501105272</Size>\n" +
                "<StorageClass>STANDARD</StorageClass>\n" +
                "</Contents>\n" +
                "<Contents>\n" +
                "<Key>[fmovies.to] The Neighbor - HD 1080p.mp4</Key>\n" +
                "<LastModified>2016-09-28T15:28:30.000Z</LastModified>\n" +
                "<ETag>\"4063a1b6a40ba03f5eb41cbe28776863-12\"</ETag>\n" +
                "<Size>738872939</Size>\n" +
                "<StorageClass>STANDARD</StorageClass>\n" +
                "</Contents>\n" +
                "<Contents>\n" +
                "<Key>[fmovies.to] The Neon Demon - HD 1080p.mp4</Key>\n" +
                "<LastModified>2016-09-25T08:25:48.000Z</LastModified>\n" +
                "<ETag>\"3dd7eb64767c9e02c134ab3b30bc2ab6-14\"</ETag>\n" +
                "<Size>883440435</Size>\n" +
                "<StorageClass>STANDARD</StorageClass>\n" +
                "</Contents>\n" +
                "<Contents>\n" +
                "<Key>[fmovies.to] The Perfect Weapon - SD.dat</Key>\n" +
                "<LastModified>2016-09-26T06:13:10.000Z</LastModified>\n" +
                "<ETag>\"a542aa2bfa9c471e37326fd3e339f285-4\"</ETag>\n" +
                "<Size>234209967</Size>\n" +
                "<StorageClass>STANDARD</StorageClass>\n" +
                "</Contents>\n" +
                "<Contents>\n" +
                "<Key>[fmovies.to] The Quarantine Hauntings - HDRip.mp4</Key>\n" +
                "<LastModified>2016-09-28T15:28:44.000Z</LastModified>\n" +
                "<ETag>\"51f7f541dce78549547eb837d8e8a7e6-4\"</ETag>\n" +
                "<Size>242513074</Size>\n" +
                "<StorageClass>STANDARD</StorageClass>\n" +
                "</Contents>\n" +
                "<Contents>\n" +
                "<Key>[fmovies.to] The Secret Life of Pets - HD 720p.mp4</Key>\n" +
                "<LastModified>2016-09-25T08:37:59.000Z</LastModified>\n" +
                "<ETag>\"71654c7d432ed04a48a9f850e7b713fb-16\"</ETag>\n" +
                "<Size>1029528391</Size>\n" +
                "<StorageClass>STANDARD</StorageClass>\n" +
                "</Contents>\n" +
                "<Contents>\n" +
                "<Key>[fmovies.to] The Windmill - HDRip.mp4</Key>\n" +
                "<LastModified>2016-09-27T18:31:23.000Z</LastModified>\n" +
                "<ETag>\"f16babd8458e4df9d7a35cf197630006-5\"</ETag>\n" +
                "<Size>293101095</Size>\n" +
                "<StorageClass>STANDARD</StorageClass>\n" +
                "</Contents>\n" +
                "<Contents>\n" +
                "<Key>[fmovies.to] Three - HDRip.dat</Key>\n" +
                "<LastModified>2016-09-26T05:39:44.000Z</LastModified>\n" +
                "<ETag>\"d80a3d7ba89d942e08b31020aabae8ff-5\"</ETag>\n" +
                "<Size>272380817</Size>\n" +
                "<StorageClass>STANDARD</StorageClass>\n" +
                "</Contents>\n" +
                "<Contents>\n" +
                "<Key>[fmovies.to] Total Frat Movie - HDRip.mp4</Key>\n" +
                "<LastModified>2016-09-25T17:48:09.000Z</LastModified>\n" +
                "<ETag>\"d076a91db0557f6583f132e016fea1f3-6\"</ETag>\n" +
                "<Size>395872686</Size>\n" +
                "<StorageClass>STANDARD</StorageClass>\n" +
                "</Contents>\n" +
                "<Contents>\n" +
                "<Key>[fmovies.to] Train to Busan - HD 720p.mp4</Key>\n" +
                "<LastModified>2016-09-25T07:09:10.000Z</LastModified>\n" +
                "<ETag>\"233d0a693306587d53d8a57d18449354-23\"</ETag>\n" +
                "<Size>1481135331</Size>\n" +
                "<StorageClass>STANDARD</StorageClass>\n" +
                "</Contents>\n" +
                "<Contents>\n" +
                "<Key>[fmovies.to] Transpecos - HD 720p.mp4</Key>\n" +
                "<LastModified>2016-09-28T15:28:54.000Z</LastModified>\n" +
                "<ETag>\"c35e7666402d89ba2f0b2a9261379380-11\"</ETag>\n" +
                "<Size>733003366</Size>\n" +
                "<StorageClass>STANDARD</StorageClass>\n" +
                "</Contents>\n" +
                "<Contents>\n" +
                "<Key>[fmovies.to] Trick or Treaters - HDRip.mp4</Key>\n" +
                "<LastModified>2016-09-26T04:54:30.000Z</LastModified>\n" +
                "<ETag>\"a077e5268292f20ea4aeeaf679441c15-4\"</ETag>\n" +
                "<Size>258938936</Size>\n" +
                "<StorageClass>STANDARD</StorageClass>\n" +
                "</Contents>\n" +
                "<Contents>\n" +
                "<Key>[fmovies.to] True Story - HD 1080p.mp4</Key>\n" +
                "<LastModified>2016-09-28T15:29:06.000Z</LastModified>\n" +
                "<ETag>\"72197bb1017e28372566a9bb1e4ecb28-15\"</ETag>\n" +
                "<Size>1003105963</Size>\n" +
                "<StorageClass>STANDARD</StorageClass>\n" +
                "</Contents>\n" +
                "<Contents>\n" +
                "<Key>[fmovies.to] UFC 203 - HD 720p.mp4</Key>\n" +
                "<LastModified>2016-09-28T15:29:48.000Z</LastModified>\n" +
                "<ETag>\"ec16a96e70997c3279ad8922a983dcbb-10\"</ETag>\n" +
                "<Size>604483673</Size>\n" +
                "<StorageClass>STANDARD</StorageClass>\n" +
                "</Contents>\n" +
                "<Contents>\n" +
                "<Key>[fmovies.to] Undercover Wife - HD 720p.mp4</Key>\n" +
                "<LastModified>2016-09-27T18:31:33.000Z</LastModified>\n" +
                "<ETag>\"fba71e3f2357807d6e01f51ea7f258fc-14\"</ETag>\n" +
                "<Size>893664340</Size>\n" +
                "<StorageClass>STANDARD</StorageClass>\n" +
                "</Contents>\n" +
                "<Contents>\n" +
                "<Key>[fmovies.to] Vacant House - HDRip.mp4</Key>\n" +
                "<LastModified>2016-09-25T18:03:54.000Z</LastModified>\n" +
                "<ETag>\"3c7bfae61b2eb4b9dbd2e01e867a579f-4\"</ETag>\n" +
                "<Size>249591229</Size>\n" +
                "<StorageClass>STANDARD</StorageClass>\n" +
                "</Contents>\n" +
                "<Contents>\n" +
                "<Key>[fmovies.to] Weiner - HD 720p.dat</Key>\n" +
                "<LastModified>2016-09-26T06:28:18.000Z</LastModified>\n" +
                "<ETag>\"3912a917098582749f1d370af6832600-22\"</ETag>\n" +
                "<Size>1457851622</Size>\n" +
                "<StorageClass>STANDARD</StorageClass>\n" +
                "</Contents>\n" +
                "<Contents>\n" +
                "<Key>[fmovies.to] Zero Days - HD 720p.mp4</Key>\n" +
                "<LastModified>2016-09-26T05:40:02.000Z</LastModified>\n" +
                "<ETag>\"bb7497b028f84e3ad419a36fd5f772a2-24\"</ETag>\n" +
                "<Size>1557619910</Size>\n" +
                "<StorageClass>STANDARD</StorageClass>\n" +
                "</Contents>\n" +
                "<Contents>\n" +
                "<Key>[fmovies.to] Zoombies - HD 1080p.mp4</Key>\n" +
                "<LastModified>2016-09-26T04:54:57.000Z</LastModified>\n" +
                "<ETag>\"2f956a51485e34535ce5eb262478e271-22\"</ETag>\n" +
                "<Size>1461090405</Size>\n" +
                "<StorageClass>STANDARD</StorageClass>\n" +
                "</Contents>\n" +
                "<Contents>\n" +
                "<Key>tnrub.mp4</Key>\n" +
                "<LastModified>2016-09-23T20:13:33.000Z</LastModified>\n" +
                "<ETag>\"2be71c3bd981b151432a32d22bc18a52-12\"</ETag>\n" +
                "<Size>794245608</Size>\n" +
                "<StorageClass>STANDARD</StorageClass>\n" +
                "</Contents>\n" +
                "</ListBucketResult>";
        Document document = Jsoup.parse(s, "", Parser.xmlParser());
        for (Element e : document.select("Contents")) {
            System.out.println(e);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    // End of variables declaration//GEN-END:variables
}
